kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-vpp-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: calico-node
          volumeMounts:
            - name: vpp-agent-binary
              mountPath: /bin/calico-vpp-agent
              readOnly: true
            - name: felix-proxy-binary
              mountPath: /bin/felix-api-proxy
              readOnly: true
        - name: vpp
          volumeMounts:
            - name: vpp-root
              mountPath: /home/hostuser/vpp
              readOnly: true
      volumes:
        # Used to put the latest binaries in the containers without rebuilding images in testing
        - name: vpp-agent-binary
          hostPath:
            type: File
            path: /host-repo/calico-vpp-agent/cmd/calico-vpp-agent
        - name: felix-proxy-binary
          hostPath:
            type: File
            path: /host-repo/calico-vpp-agent/cmd/felix-api-proxy
        - name: vpp-root
          hostPath:
            type: Directory
            path: /host-repo/vpp-manager/vpp_build

